import fs from "fs/promises";
import path from "path";
import crypto from "crypto";

export type Bucket = "public" | "private";

function root() {
  return process.env.STORAGE_DIR
    ? path.resolve(process.env.STORAGE_DIR)
    : path.join(process.cwd(), "storage");
}

function bucketDir(bucket: Bucket) {
  return path.join(root(), bucket);
}

/**
 * Keys are generated by us, never supplied by a client, but `readFile` is
 * reachable with a path segment from the URL so the shape is enforced here and
 * the resolved path is asserted to stay inside its bucket.
 */
function resolveKey(bucket: Bucket, key: string) {
  if (!/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,127}$/.test(key) || key.includes("..")) {
    throw new Error("Invalid storage key.");
  }
  const dir = bucketDir(bucket);
  const target = path.resolve(dir, key);
  if (target !== path.join(dir, key)) throw new Error("Invalid storage key.");
  return target;
}

export async function saveFile(
  bucket: Bucket,
  file: File
): Promise<{ key: string; size: number; mime: string; name: string }> {
  const dir = bucketDir(bucket);
  await fs.mkdir(dir, { recursive: true });

  const ext = path.extname(file.name).slice(0, 12).toLowerCase().replace(/[^a-z0-9.]/g, "");
  const key = `${crypto.randomUUID()}${ext === "." ? "" : ext}`;
  const target = resolveKey(bucket, key);

  const buffer = Buffer.from(await file.arrayBuffer());
  await fs.writeFile(target, buffer, { flag: "wx" });

  return {
    key,
    size: buffer.byteLength,
    mime: file.type || "application/octet-stream",
    name: path.basename(file.name).slice(0, 200),
  };
}

export async function readFile(bucket: Bucket, key: string) {
  return fs.readFile(resolveKey(bucket, key));
}

export async function deleteFile(bucket: Bucket, key: string) {
  await fs.rm(resolveKey(bucket, key), { force: true });
}

export const MAX_UPLOAD_BYTES =
  Math.max(1, Number(process.env.MAX_UPLOAD_MB) || 50) * 1024 * 1024;

/**
 * SVG is deliberately excluded: it is served from this origin, so an uploaded
 * SVG would be a stored cross-site scripting vector.
 */
export const ALLOWED_IMAGE_MIME = ["image/png", "image/jpeg", "image/webp", "image/gif"];

export const IMAGE_EXTENSION: Record<string, string> = {
  "image/png": ".png",
  "image/jpeg": ".jpg",
  "image/webp": ".webp",
  "image/gif": ".gif",
};
